name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Build app
        run: ./scripts/buildprod.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image southamerica-east1-docker.pkg.dev/virtual-concept-440122-a1/notelyrepo/notely:latest --region southamerica-east1 --allow-unauthenticated --project virtual-concept-440122-a1 --max-instances=4

